### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by jfuruness** [mvp/uhubctl#351]
After running sudo make install I get this error:

```
install -m 755 -d /usr/sbin
Traceback (most recent call last):
  File "/usr/local/bin/install", line 33, in <module>
    sys.exit(load_entry_point('lib-installer', 'console_scripts', 'install')())
  File "/usr/local/bin/install", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.8/importlib/metadata.py", line 504, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: lib-installer
make: *** [Makefile:44: install] Error 1
```

I am running ubuntu 20.04. I've googled this error but can't seem to find anything on it. Please advise.

**Comment by mvp** [comment]
`sudo make install` should not invoke anything python related, not sure what is wrong with your particular OS install.
As a workaround, you can simply copy `uhubctl` executable somewhere in your `PATH`, e.g. this should work pretty much the same as `sudo make install`:
```
    sudo cp uhubctl /usr/sbin
```
